FROM python:alpine3.21

WORKDIR /app

COPY . .

RUN pip3 install -r requirements.txt
RUN pip3 install python-dotenv
RUN apt-get -y update 
RUN apt-get -y install curl
RUN curl http://checkip.amazonaws.com >> .env

EXPOSE 5000 

CMD ["python", "app.py"]
