FROM node:22-alpine

# Set the working directory
WORKDIR /app    
# Copy the rest of the application code
COPY . .
# Install dependencies
RUN npm install

# Expose the port the app runs on 
# vite apps run on port 5173 by default
EXPOSE 5173
# Set the command to run the application
# Start the application
CMD ["npm", "run" , "dev" , "--", "--host"]