
# -------------------------------
# API (Node.js Express) 
# ------------------------------- 

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: api-dep 
  namespace: url-shortener
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: api-dep-pod 
  template: 
    metadata: 
      labels: 
        app: api-dep-pod 
    spec: 
      containers:
        - name: api
          image: loulah/url-shortener-api:latest
          command: ["sh", "-c", "ulimit -n 65536 && npm run start"]
          ports: 
            - containerPort: 8001 
          env: 
            - name: MONGO_URI 
              value: "mongodb+srv://${{DB_CPASSWORD}}:${{DB_CPASSWORD}}@development.zgc1n.mongodb.net/?retryWrites=true&w=majority&appName=Development" 
            - name: PORT 
              value: "8001" 
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
---

apiVersion: v1 
kind: Service 
metadata: 
  name: api-svc
  namespace: url-shortener 
spec: 
  type: ClusterIP
  selector: 
    app: api-dep-pod 
  ports:
  - port: 8001 
    targetPort: 8001 
