
# -------------------------------
# Grafana
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dep-pod
  template:
    metadata:
      labels:
        app: grafana-dep-pod
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.1.4
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: 'true'
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: url-shortener
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


---

apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: grafana-dep-pod
  ports:
    - port: 3000
      targetPort: 3000
